src_language: de
target_langs: [en, fr, sp]
translator: google
src_filenames: ['*.md']  # Verarbeitet alle .md-Dateien in src_dir
src_dir: DE
output_dir: DEV
insert_warnings: true
threads: -1
proxy:
  enable: false
  address: ""
  port: ""
  username: ""
  password: ""
warnings_map:
  en: "Warning: This page is translated by MACHINE, which may lead to POOR QUALITY or INCORRECT INFORMATION, please read with CAUTION!"
  fr: "Avertissement : Cette page est traduite par MACHINE, ce qui peut entraîner une MAUVAISE QUALITÉ ou des INFORMATIONS INCORRECTES, veuillez lire avec PRUDENCE !"
  sp: "Advertencia: ¡Esta página está traducida por MÁQUINA, lo que puede llevar a BAJA CALIDAD o INFORMACIÓN INCORRECTA, lea con PRECAUCIÓN!"