# config.yaml
src_language: de
target_langs:
  - en
  - fr
  - es
src_dir: DE
output_dir: DEV # Dies ist der Ordner, in den die übersetzten Dateien geschrieben werden
insert_warnings: true
warnings_mapping:
  en: "Warning: This page is translated by MACHINE, which may lead to POOR QUALITY or INCORRECT INFORMATION, please read with CAUTION!"
  fr: "Avertissement : Cette page is translated by MACHINE, which may lead to POOR QUALITY or INCORRECT INFORMATION, please read with CAUTION!"
  es: "Advertencia: This page is translated by MACHINE, which may lead to POOR QUALITY or INCORRECT INFORMATION, please read with CAUTION!"

# NEU: Hugging Face Modelle, die verwendet werden sollen
translation_models:
  de-en: "Helsinki-NLP/opus-mt-de-en"
  de-fr: "Helsinki-NLP/opus-mt-de-fr"
  de-es: "Helsinki-NLP/opus-mt-de-es"
  # Optional: Wenn du ein großes multilinguales Modell verwenden möchtest (z.B. für alle):
  # multi: "facebook/m2m100_418M"