src_language: de
target_langs:
  - en
  # - fr
  # - es
src_dir: DE
output_dir: DEV
insert_warnings: true
warnings_mapping:
  en: "Yo, Maschinenübersetzung! Kann mal danebenliegen, also chillig lesen!"
  # fr: "Hé, trad auto ici ! Ça peut foirer, lis cool !"
  # es: "¡Ojo, traducción por máquina! Puede patinar, léelo tranqui!"
front_matter_transparent_keys:
  - date
  - slug
front_matter_key_value_keys:
  - title
  - description
max_chunk_length: 2000