name: Translate Markdown with Free-Markdown-Translator

on:
  push:
    branches:
      - main # Passe dies an deinen Standard-Branch an (z.B. 'master')
    paths:
      - 'DE/**'          # Trigger, wenn sich etwas im DE-Ordner ändert
      - 'config.yml'     # Trigger, wenn sich config.yml ändert
      - '.github/workflows/translate_docs.yml' # Trigger, wenn sich der Workflow selbst ändert
  workflow_dispatch: # Ermöglicht das manuelle Ausführen des Workflows über die GitHub UI

jobs:
  translate:
    runs-on: ubuntu-latest # Verwendet den neuesten Ubuntu Linux Runner
    permissions:
      contents: write # Dies gewährt dem standardmäßigen GITHUB_TOKEN Schreibberechtigungen für das Repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Klonen des eigenen Repositories in die Runner-Umgebung

      - name: Set up Python
        uses: actions/setup-python@v5 # Einrichten einer Python-Umgebung
        with:
          python-version: '3.10' # Angabe der zu verwendenden Python-Version

      - name: Upgrade pip and setuptools
        run: |
          python -m pip install --upgrade pip setuptools # Sicherstellen, dass pip aktuell ist

      - name: Install Free Markdown Translator as a Python Package
        run: |
          CLONE_DIR="Free-Markdown-Translator"
          REPO_URL="https://github.com/CrazyMayfly/Free-Markdown-Translator.git"
          
          echo "Cloning $REPO_URL into $CLONE_DIR for package installation..."
          git clone "$REPO_URL" "$CLONE_DIR" || { echo "ERROR: Failed to clone repository for installation."; exit 1; }
          
          echo "Listing contents of cloned directory ($CLONE_DIR) before installation:"
          ls -la "$CLONE_DIR/" || { echo "ERROR: Could not list contents of $CLONE_DIR."; exit 1; }
          
          echo "Attempting to install Free-Markdown-Translator as a local package..."
          # *** KORRIGIERTER INSTALLATIONSBEFEHL ***
          # Der Punkt './' erzwingt die lokale Installation aus dem Verzeichnis
          pip install "./$CLONE_DIR" || { echo "ERROR: Failed to install Free-Markdown-Translator."; exit 1; }
          # Alternative (oft empfohlen für lokale Entwicklung/Test): pip install -e "$CLONE_DIR"

          echo "Installation successful."
        # env: (API-Keys, falls benötigt, als GitHub Secret speichern)
        #   GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_TRANSLATE_API_KEY_JSON }}

      - name: Create output directories for translated files
        run: |
          mkdir -p DEV/en
          mkdir -p DEV/fr
          mkdir -p DEV/sp

      - name: Run translation via Python Module
        # Nach der Installation kann das Tool als Python-Modul aufgerufen werden.
        run: python -m markdown_translator config.yaml
        env:
          PYTHONIOENCODING: utf-8

      - name: Commit and push changes
        id: commit_changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions-bot@users.noreply.github.com"

          git add DEV/

          if ! git diff --staged --quiet; then
            echo "No changes in translated files detected. Skipping commit."
            echo "pushed_changes=false" >> "$GITHUB_OUTPUT"
          else
            echo "Changes detected, committing and pushing..."
            git commit -m "Automated translation: Update DEV folder with EN, FR, SP [skip ci]"
            git push
            echo "pushed_changes=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Verify successful push
        if: steps.commit_changes.outputs.pushed_changes == 'true'
        run: echo "Translation successful and changes pushed to main branch."