name: Translate Markdown DE→EN

on:
  push:
    branches: [main]
    paths:
      - 'DE/**'
      - 'config.yml'
      - '.github/workflows/translate_docs.yml'
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Wichtig für git diff

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/CrazyMayfly/Free-Markdown-Translator.git
          pip install pyyaml deep-translator

      - name: Verify config file exists
        id: check_config
        run: |
          if [ ! -f "config.yml" ]; then
            echo "Creating default config.yml..."
            cat > config.yml <<EOL
            source_language: "de"
            target_language: "en"
            translator: "google"
            files:
              - source_path: "DE/"
                target_path: "EN/"
            EOL
          else
            echo "Using existing config.yml"
          fi

      - name: Create output directories
        run: |
          mkdir -p EN
          mkdir -p FR
          mkdir -p ES

      - name: Run translation
        run: |
          python -m markdown_translator config.yml
        env:
          PYTHONIOENCODING: utf-8

      - name: Commit and push changes
        id: commit_changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Check for changes in all target directories
          git add EN/ FR/ ES/
          
          if git diff --cached --quiet; then
            echo "No changes to commit"
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected, committing..."
            git commit -m "Auto-translated: DE→EN/FR/ES [skip ci]"
            git push
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi

      - name: Post-translation cleanup
        if: always()
        run: |
          echo "Workflow completed with status: ${{ job.status }}"
          if [ "${{ job.status }}" == "success" ]; then
            echo "Translation successful"
          else
            echo "::warning::Translation workflow had issues"
          fi