name: Translate Markdown

on:
  push:
    paths:
      - 'DE/**'
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip setuptools

      - name: Install Free Markdown Translator
        run: |
          git clone https://github.com/CrazyMayfly/Free-Markdown-Translator.git
          pip install ./Free-Markdown-Translator

      - name: Run translation
        run: |
          python -m markdown_translator config.yaml
