name: Translate Markdown

on:
  push:
    branches: [main]
    paths:
      - 'DE/**'
      - 'config.yml'
      - '.github/workflows/translate.yml'

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml deep-translator

      - name: Verify config file exists
        id: check_config
        run: |
          if [ ! -f "config.yml" ]; then
            echo "Creating default config.yml..."
            cat > config.yml << EOL
            src_language: de
            target_langs: [en, fr, sp]
            translator: google
            src_filenames: ['index']
            src_dir: DE
            output_dir: DEV
            insert_warnings: true
            EOL
          else
            echo "Using existing config.yml"
          fi

      - name: Run translation
        run: |
          python src/markdown_translator.py --config config.yml

      - name: Commit and push changes
        id: commit_changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add DEV/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            echo "Changes detected, committing..."
            git commit -m "Auto-translated: DE→EN/FR/SP [skip ci]"
            git push
          fi

      - name: Post-translation cleanup
        if: always()
        run: |
          echo "Workflow completed with status: ${{ job.status }}"
          if [ "${{ job.status }}" == "success" ]; then
            echo "Translation successful"
          else
            echo "::warning::Translation workflow had issues"
          fi
