name: Markdown mit Argos Translate übersetzen
on:
  push:
    branches: [main]
    paths:
      - 'DE/**'
      - 'config.yaml'
      - '.github/scripts/translate_with_argos.py'
      - '.github/workflows/translate.yml'
  schedule:
    - cron: '0 0 * * *' # Jeden Tag um Mitternacht UTC
jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Repo klonen
        uses: actions/checkout@v4
      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Python-Pakete installieren
        run: |
          pip install argostranslate argos-translate-files pyyaml
      - name: Argos Sprachpakete cachen
        uses: actions/cache@v4
        with:
          path: ~/.local/share/argos-translate
          key: ${{ runner.os }}-argos-${{ hashFiles('.github/workflows/translate.yml', 'config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-argos-
      - name: Zielordner anlegen
        run: |
          mkdir -p DEV/en
          mkdir -p DEV/fr
          mkdir -p DEV/es
          mkdir -p DE
      - name: Übersetzungsskript abfeuern
        run: python .github/scripts/translate_with_argos.py
      - name: Übersetzungen checken
        run: |
          if [ -z "$(find DEV -maxdepth 2 -type f -name '*.md')" ]; then
            echo "::warning::Keine Markdowns in DEV gefunden."
            exit 0
          else
            echo "Übersetzungen da, alles klar!"
          fi
      - name: Änderungen pushen
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions-bot@users.noreply.github.com"
          git add DEV/
          if git diff --cached --quiet; then
            echo "Nix zu committen"
          else
            echo "Änderungen da, wird gepusht..."
            git commit -m "Auto-übersetzt mit Argos: DE→EN/FR/ES [skip ci]"
            git push
        