name: Translate Markdown Files with Free-Markdown-Translator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Berechtigungen für GITHUB_TOKEN setzen
permissions:
  contents: write
  pull-requests: write

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Vollständige History für Git-Operationen

      # Python-Umgebung einrichten
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Free-Markdown-Translator und Abhängigkeiten installieren
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install translators pyyaml

      # Konfigurationsdatei erstellen
      - name: Create config.yaml
        run: |
          cat << EOF > config.yaml
          src_language: de
          target_langs: [en, fr, sp]
          translator: google
          src_filenames: ['index']
          src_dir: DE
          output_dir: DEV
          insert_warnings: true
          threads: -1
          proxy:
            enable: false
            address: 127.0.0.1
            port: 1234
            username: ""
            password: ""
          warnings_mapping:
            en: "Warning: This page is translated by MACHINE, which may lead to POOR QUALITY or INCORRECT INFORMATION, please read with CAUTION!"
            fr: "Avertissement : Cette page est traduite par MACHINE, ce qui peut entraîner une MAUVAISE QUALITÉ ou des INFORMATIONS INCORRECTES, veuillez lire avec PRUDENCE !"
            sp: "Advertencia: ¡Esta página está traducida por MÁQUINA, lo que puede llevar a BAJA CALIDAD o INFORMACIÓN INCORRECTA, lea con PRECAUCIÓN!"
          EOF

      # Free-Markdown-Translator klonen und ausführen
      - name: Run Free-Markdown-Translator
        run: |
          git clone https://github.com/CrazyMayfly/Free-Markdown-Translator.git
          cd Free-Markdown-Translator
          cp ../config.yaml .
          python src/main.py ../DE
          cp -r translated/* ../DEV/
          cd ..

      # Übersetzte Dateien committen
      - name: Commit Translated Files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add DEV/*.md
          git commit -m "Add translated Markdown files (en, fr, sp)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}