name: Translate Markdown with Hugging Face

on:
  push:
    branches: [main]
    paths:
      - 'DE/**'
      - 'config.yaml'
      - '.github/scripts/translate_with_huggingface.py'
      - '.github/workflows/translate.yml'

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install transformers pyyaml torch sentencepiece sacremoses

      - name: Clone NLTK from GitHub
        run: |
          git clone --branch 3.8.1 https://github.com/nltk/nltk.git
          cd nltk
          python setup.py install
          cd ..

      - name: Cache NLTK data
        uses: actions/cache@v4
        with:
          path: ~/.nltk_data
          key: ${{ runner.os }}-nltk-${{ hashFiles('.github/workflows/translate.yml', '.github/scripts/translate_with_huggingface.py', 'config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-nltk-

      - name: Download NLTK data
        run: |
          mkdir -p ~/.nltk_data
          echo "NLTK_DATA=~/.nltk_data" >> $GITHUB_ENV
          python -c "import nltk; nltk.download('punkt', download_dir='~/.nltk_data', quiet=True)"
          python -c "import nltk; nltk.download('punkt_tab', download_dir='~/.nltk_data', quiet=True)"
          echo "Inhalt von ~/.nltk_data nach Download:"
          ls -R ~/.nltk_data || true

      - name: Cache Hugging Face models
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface
          key: ${{ runner.os }}-huggingface-${{ hashFiles('.github/scripts/translate_with_huggingface.py', 'config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-huggingface-

      - name: Check if any language directory is empty
        id: check-dev
        run: |
          retranslate=false
          for lang in en fr es; do
            if [ -z "$(find DEV/$lang -maxdepth 1 -type f)" ]; then
              echo "DEV/$lang ist leer, alle Dateien werden neu übersetzt."
              retranslate=true
              break
            fi
          done
          if [ "$retranslate" = "true" ]; then
            echo "Lösche DEV-Inhalte, um alles neu zu übersetzen."
            rm -rf DEV/*
          else
            echo "Kein leerer Sprachordner, selektive Übersetzung."
          fi
          echo "retranslate=$retranslate" >> $GITHUB_ENV
          # Erstelle Ausgabeordner
          mkdir -p DEV/en DEV/fr DEV/es DE

      - name: List files for debug
        run: |
          echo "Inhalt von DE/:"
          find DE/ -type f -name '*.md' || true
          echo "Inhalt des Skript-Verzeichnisses (.github/scripts/):"
          ls -l .github/scripts/ || true
          echo "Inhalt von Root (config.yaml):"
          ls -l config.yaml || true
          echo "Inhalt von DEV/ vor Übersetzung:"
          find DEV/ -type f || true

      - name: Run Hugging Face translation script
        run: python .github/scripts/translate_with_huggingface.py

      - name: Verify translation output
        run: |
          echo "Inhalt von DEV/en:"
          find DEV/en -type f || true
          echo "Inhalt von DEV/fr:"
          find DEV/fr -type f || true
          echo "Inhalt von DEV/es:"
          find DEV/es -type f || true
          if [ -z "$(find DEV -maxdepth 2 -type f -name '*.md')" ]; then
            echo "::error::Keine übersetzten Markdown-Dateien im DEV-Verzeichnis gefunden."
            exit 1
          else
            echo "Übersetzte Dateien gefunden. Der Workflow war erfolgreich."
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions-bot@users.noreply.github.com"
          git add DEV/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            echo "Changes detected, committing..."
            git commit -m "Auto-translated (Hugging Face): DE→EN/FR/ES"
            git push
          fi