name: Translate Markdown

on:
  push:
    branches: [main]
    paths:
      - 'DE/**'
      - '.github/config.yaml' # <-- Jetzt konsequent .yaml
      - '.github/scripts/generate_translate_script.sh'
      - '.github/workflows/translate.yml'

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install general Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir pyyaml translators pysocks colorlog

      - name: Read config.yaml
        run: |
          if [ -f .github/config.yaml ]; then
            echo "Using existing config.yaml"
            cat .github/config.yaml
          else
            echo "::error::config.yaml not found at .github/config.yaml"
            exit 1
          fi

      - name: Copy config.yaml to root # Kopiert die Datei, damit MdTranslater sie findet
        run: cp .github/config.yaml config.yaml 

      - name: Clone Free-Markdown-Translator
        run: |
          git clone https://github.com/CrazyMayfly/Free-Markdown-Translator.git

      - name: Verify Free-Markdown-Translator
        run: |
          if [ -f Free-Markdown-Translator/src/MarkdownTranslator.py ]; then
            echo "Free-Markdown-Translator MarkdownTranslator.py found"
            ls -l Free-Markdown-Translator/src/
          else
            echo "::error::Free-Markdown-Translator MarkdownTranslator.py not found"
            exit 1
          fi

      - name: Generate translate.py wrapper script
        run: bash .github/scripts/generate_translate_script.sh

      - name: Run translation
        # Jetzt sollte MdTranslater die kopierte config.yaml korrekt laden können.
        run: python translate.py

      - name: Commit and push changes
        id: commit_changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions-bot@users.noreply.github.com"
          
          git add DEV/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            echo "Changes detected, committing..."
            git commit -m "Auto-translated: DE→EN/FR/ES [skip ci]"
            git push
          fi

      - name: Post-translation cleanup
        if: always()
        run: |
          echo "Workflow completed with status: ${{ job.status }}"
          if [ "${{ job.status }}" = "success" ]; then
            echo "Translation successful"
          else
            echo "::warning::Translation workflow had issues"
          fi