name: Translate Markdown

on:
  push:
    branches: [main]
    paths:
      - 'DE/**'
      - '.github/config.yml' # <-- Pfad hier korrigiert
      - '.github/scripts/create_wrapper.py' # <-- Auch diesen Pfad hinzufügen, falls er sich ändert
      - '.github/workflows/translate.yml'

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir pyyaml translators pysocks colorlog

      - name: Read config.yml
        run: |
          # Der Pfad ist hier bereits korrekt: .github/config.yml
          if [ -f .github/config.yml ]; then
            echo "Using existing config.yml"
            cat .github/config.yml # Optional: Inhalt zur Überprüfung ausgeben
          else
            echo "::error::config.yml not found at .github/config.yml" # Klarere Fehlermeldung
            exit 1
          fi

      - name: Clone Free-Markdown-Translator
        run: |
          git clone https://github.com/CrazyMayfly/Free-Markdown-Translator.git

      - name: Verify Free-Markdown-Translator
        run: |
          if [ -f Free-Markdown-Translator/src/MarkdownTranslator.py ]; then
            echo "Free-Markdown-Translator MarkdownTranslator.py found"
            ls -l Free-Markdown-Translator/src/
          else
            echo "::error::Free-Markdown-Translator MarkdownTranslator.py not found"
            exit 1
          fi

      - name: Install Free-Markdown-Translator (as a Python package)
        run: |
          cd Free-Markdown-Translator
          python -m pip install -e .

      - name: Create wrapper script
        # Führt das Skript aus, das translate.py erstellt.
        # Wichtig: Der Pfad ist relativ zum Root des Repositories.
        run: python .github/scripts/create_wrapper.py

      - name: Run translation
        # Führt das soeben erstellte translate.py aus.
        # translate.py wird im Root des Repositories erstellt.
        run: python translate.py

      - name: Commit and push changes
        id: commit_changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions-bot@users.noreply.github.com"
          git add DEV/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            echo "Changes detected, committing..."
            git commit -m "Auto-translated: DE→EN/FR/ES [skip ci]"
            git push
          fi

      - name: Post-translation cleanup
        if: always()
        run: |
          echo "Workflow completed with status: ${{ job.status }}"
          if [ "${{ job.status }}" = "success" ]; then
            echo "Translation successful"
          else
            echo "::warning::Translation workflow had issues"
          fi