name: Translate Markdown with Free-Markdown-Translator

on:
  push:
    branches:
      - main # Diesen Branch anpassen (z.B. 'master')
    paths:
      - 'DE/**'
      - 'config.yml'
      - '.github/workflows/translate_docs.yml'
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Upgrade pip and setuptools
        run: |
          python -m pip install --upgrade pip setuptools

      - name: Clone Free Markdown Translator and Verify Script
        id: clone_translator
        run: |
          CLONE_DIR="Free-Markdown-Translator" # Name des Verzeichnisses, in das das Repo geklont wird
          REPO_URL="https://github.com/CrazyMayfly/Free-Markdown-Translator.git"
          SCRIPT_PATH="$CLONE_DIR/markdown_translator.py"

          echo "Attempting to clone $REPO_URL into $CLONE_DIR..."
          git clone "$REPO_URL" "$CLONE_DIR" || { echo "ERROR: Failed to clone repository."; exit 1; }

          echo "Listing contents of cloned directory ($CLONE_DIR) to verify script presence:"
          ls -la "$CLONE_DIR/" || { echo "ERROR: Could not list contents of $CLONE_DIR."; exit 1; }

          if [ -f "$SCRIPT_PATH" ]; then
            echo "Success: markdown_translator.py found at $SCRIPT_PATH."
          else
            echo "ERROR: markdown_translator.py NOT FOUND at $SCRIPT_PATH after cloning."
            echo "Please check the repository structure or if the clone was incomplete."
            exit 1
          fi
        # env: (API-Keys, falls benötigt)

      - name: Create output directories for translated files
        run: |
          mkdir -p DEV/en
          mkdir -p DEV/fr
          mkdir -p DEV/sp

      - name: Run translation script directly
        # --- WICHTIGE ÄNDERUNG HIER ---
        working-directory: Free-Markdown-Translator # <-- Setzt das Arbeitsverzeichnis für diesen Schritt
        run: python markdown_translator.py ../config.yml # <-- Pfad zum Skript und zur config.yml anpassen
        env:
          PYTHONIOENCODING: utf-8

      - name: Commit and push changes
        id: commit_changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions-bot@users.noreply.github.com"

          git add DEV/

          if ! git diff --staged --quiet; then
            echo "No changes in translated files detected. Skipping commit."
            echo "pushed_changes=false" >> "$GITHUB_OUTPUT"
          else
            echo "Changes detected, committing and pushing..."
            git commit -m "Automated translation: Update DEV folder with EN, FR, SP [skip ci]"
            git push
            echo "pushed_changes=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Verify successful push
        if: steps.commit_changes.outputs.pushed_changes == 'true'
        run: echo "Translation successful and changes pushed to main branch."