name: Markdown mit Argos Translate übersetzen
on:
  push:
    branches: [main]
    paths:
      - 'DE/**'
      - 'config.yaml'
      - '.github/scripts/translate_with_argos.py'
      - '.github/workflows/translate.yml'
      - 'models/*.argosmodel'
  schedule:
    - cron: '0 0 * * *'  # Jeden Tag um Mitternacht UTC
jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: .  # Repo-Root als Arbeitsverzeichnis
    steps:
      - name: Repo klonen
        uses: actions/checkout@v4
      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Python-Umgebung prüfen
        run: |
          echo "Python-Version: $(python3 --version)"
          echo "Pip-Version: $(pip --version)"
          pip cache dir
      - name: Python-Pakete installieren
        run: |
          set -x
          pip install --no-cache-dir argostranslate==1.9.2 pyyaml==6.0.2
      - name: Installierte Pakete prüfen
        run: |
          echo "Installierte Pakete:"
          pip list
      - name: Argos-Version prüfen
        run: |
          python3 -c "import argostranslate; print('Argos-Version:', getattr(argostranslate, '__version__', 'unbekannt'))"
      - name: Verfügbare Argos-Sprachpakete prüfen
        run: |
          python3 -c "import argostranslate.package; print('Verfügbare Pakete:', [f'{p.from_code}->{p.to_code}' for p in argostranslate.package.get_available_packages()])"
      - name: Argos-Modelle herunterladen und committen
        run: |
          set -x
          echo "Lade Argos-Modelle..."
          mkdir -p models
          # Modelle herunterladen
          curl -o models/translate-en_fr-1_9.argosmodel https://argos-net.com/v1/translate-en_fr-1_9.argosmodel || { echo "::warning::en_fr Download fehlgeschlagen!"; exit 1; }
          curl -o models/translate-en_es-1_0.argosmodel https://argos-net.com/v1/translate-en_es-1_0.argosmodel || { echo "::warning::en_es Download fehlgeschlagen!"; exit 1; }
          # Umbenennen für translate_with_argos.py
          mv models/translate-en_fr-1_9.argosmodel models/en_fr_1.9.argosmodel || { echo "::warning::Umbenennen von en_fr fehlgeschlagen!"; exit 1; }
          mv models/translate-en_es-1_0.argosmodel models/en_es_1.0.argosmodel || { echo "::warning::Umbenennen von en_es fehlgeschlagen!"; exit 1; }
          echo "Prüfe Modelle..."
          ls -l models/*.argosmodel || echo "::warning::Keine .argosmodel-Dateien gefunden!"
          if ls models/en_fr_1.9.argosmodel >/dev/null 2>&1 && ls models/en_es_1.0.argosmodel >/dev/null 2>&1; then
            echo "en_fr_1.9 und en_es_1.0 Modelle vorhanden, alles klar!"
          else
            echo "::error::en_fr_1.9 oder en_es_1.0 Modelle fehlen, Übersetzung für fr/es wird übersprungen."
            exit 1
          fi
          git add models/*.argosmodel || true
          if git diff --staged --quiet; then
            echo "Keine Model-Änderungen, chill!"
          else
            echo "Neue Modelle, commiten..."
            git config --global user.name "GitHub Actions Bot"
            git config --global user.email "github-actions-bot@users.noreply.github.com"
            git commit -m "Add en->fr, en->es Argos models [skip ci]" || echo "::warning::Kein Commit nötig."
            git push || echo "::warning::Git push fehlgeschlagen, fahre fort."
          fi
      - name: Argos-Sprachpakete cachen
        uses: actions/cache@v4
        with:
          path: ~/.local/share/argos-translate
          key: ${{ runner.os }}-argos-${{ hashFiles('.github/workflows/translate.yml', 'config.yaml', 'models/*.argosmodel') }}
          restore-keys: |
            ${{ runner.os }}-argos-
      - name: Zielordner anlegen
        run: |
          mkdir -p DEV/en
          mkdir -p DEV/fr
          mkdir -p DEV/es
          mkdir -p DE
      - name: Übersetzungsskript prüfen und ausführen
        run: |
          set -x
          echo "Prüfe Übersetzungsskript..."
          ls -l .github/scripts/translate_with_argos.py || { echo "::error::Übersetzungsskript .github/scripts/translate_with_argos.py nicht gefunden!"; exit 1; }
          test -f .github/scripts/translate_with_argos.py || { echo "::error::Skript .github/scripts/translate_with_argos.py existiert nicht!"; exit 1; }
          echo "Führe Skript aus..."
          python3 .github/scripts/translate_with_argos.py
      - name: Übersetzungen checken
        run: |
          if [ -z "$(find DEV -maxdepth 2 -type f -name '*.md')" ]; then
            echo "::warning::Keine Markdowns in DEV gefunden."
            exit 0
          else
            echo "Übersetzungen gefunden, alles klar!"
          fi
      - name: Änderungen pushen
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions-bot@users.noreply.github.com"
          git add DEV/
          if git diff --staged --quiet; then
            echo "Nix zu commiten, chill!"
          else
            echo "Änderungen da, pushen wir..."
            git commit -m "Auto-übersetzt mit Argos: DE→EN/FR/ES [skip ci]"
            git push
          fi