name: Translate Markdown Files with Free Markdown Translator

on:
  push:
    branches:
      - main
    paths:
      - 'DE/**/*.md' # Auslösen, wenn sich .md-Dateien im DE/-Ordner ändern
      - 'src/**' # Auslösen, wenn sich Quellcode des Translators ändert (falls Sie ihn im Repo haben)
      - '.github/workflows/translate-markdown.yml' # Auslösen, wenn sich der Workflow selbst ändert

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Wichtig für das spätere Committen der Übersetzungen

    # Setup Python (korrekt für Free Markdown Translator)
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Verwenden der neuesten Python 3 Version

    # Installieren der Python-Abhängigkeiten
    - name: Install Free Markdown Translator Dependencies
      # Der Free-Markdown-Translator benötigt 'translators' und 'PyYAML'
      # Wir gehen davon aus, dass sich die requirements.txt im 'src'-Ordner befindet
      run: pip install -r src/requirements.txt

    # Konfigurationsdatei für Free Markdown Translator erstellen
    - name: Create config.yaml
      # Diese Konfigurationsdatei steuert den Free-Markdown-Translator
      run: |
        cat <<EOF > config.yaml
        src_language: de
        target_langs:
          - en
          - es
        src_dir: DE/ # Der Ordner, der die Quelldateien enthält
        output_dir: DEV/ # Der Zielordner. Der Translator erstellt hier die Unterordner für Sprachen (DEV/en, DEV/es).
        translator_engine: google # Oder eine andere unterstützte Engine wie 'bing', 'tencent', 'baidu', etc.
        insert_warning: true
        warning_message: "This document was translated using machine translation and may contain errors. Please review carefully."
        
        # Optional: Weitere Einstellungen, die im originalen config.yaml Beispiel vorhanden waren.
        # Beachten Sie, dass der Python-Translator eine einzelne 'warning_message' hat, nicht 'warnings_mapping'.
        # Die Front-Matter-Einstellungen hier sind sehr detailliert, übernehmen Sie nur die, die Sie wirklich brauchen.
        # threads: 4 # Kann Performance verbessern
        # proxy:
        #   enable: false
        # front_matter_transparent_keys:
        #   - date
        #   - slug
        #   - toc
        #   - image
        #   - comments
        #   - readingTime
        #   - license
        #   - style
        # front_matter_key_value_keys:
        #   - title
        #   - description
        # front_matter_key_value_array_keys:
        #   - tags
        #   - categories
        #   - keywords
        EOF

    # Übersetzen der Markdown-Dateien
    - name: Translate Markdown files
      # Der Translator liest die Pfade aus der config.yaml und verarbeitet alle Dateien im src_dir
      run: python src/main.py

    # Änderungen committen
    - name: Commit translations
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Fügen Sie alle Änderungen im DEV/-Ordner zum Staging hinzu
        git add DEV/
        
        # Prüfen, ob es tatsächlich Änderungen zum Committen gibt
        # (Um leere Commits bei unveränderten Übersetzungen zu vermeiden)
        if ! git diff --cached --exit-code; then
          echo "No changes to commit (translations are up to date)."
        else
          git commit -m "Automated: Translate Markdown files from DE/ to DEV/en and DEV/es"
          git push
        fi
      env:
        # Der Standard-GITHUB_TOKEN hat die notwendigen Berechtigungen zum Pushen
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}